version: '0.1'

services:
  springboot_app: 
    image: revapp
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: rev_backend
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    networks:
      - rev_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://rev_sql:3306/revshop_docker
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  mysql:
    image: mysql:latest
    container_name: rev_sql
    ports:
      - "3304:3306"
    networks:
      - rev_network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: revshop_docker

networks:
  rev_network:
